import React from 'react';
import { BookOpen, Clock3, FileText, GraduationCap, Languages, Lock, PlayCircle, ShieldCheck } from 'lucide-react';

interface Props { onOpenDocumentation: () => void; }

export default function CommercialTrainingCenter({ onOpenDocumentation }: Props) {
  const courses = [
    { title: 'Inglés comercial', description: 'Conversaciones, reuniones y negociación con clientes internacionales.', modules: 12, Icon: Languages, accent: 'from-cyan-400/20 to-blue-500/5' },
    { title: 'Closing de alto valor', description: 'Diagnóstico, propuesta, objeciones y cierre consultivo.', modules: 8, Icon: GraduationCap, accent: 'from-violet-400/20 to-fuchsia-500/5' },
    { title: 'Procesos Althera', description: 'Metodología interna, calidad de datos y operativa comercial.', modules: 6, Icon: ShieldCheck, accent: 'from-lime-400/20 to-emerald-500/5' },
  ];

  return <div className="space-y-6 animate-fade-in">
    <section className="relative overflow-hidden rounded-3xl border border-white/[0.07] bg-[radial-gradient(circle_at_85%_20%,rgba(163,230,53,.12),transparent_30%),linear-gradient(135deg,#0b1017,#080b10)] p-6 sm:p-8"><GraduationCap className="absolute -bottom-8 right-4 h-40 w-40 text-white/[0.025]"/><div className="relative"><p className="text-[9px] font-black uppercase tracking-[.28em] text-lime-300">Althera Academy</p><h2 className="mt-2 text-3xl font-black text-white">Formación comercial</h2><p className="mt-2 max-w-xl text-xs leading-5 text-slate-400">Tu espacio de aprendizaje, procesos y documentación oficial. Los cursos se habilitarán progresivamente.</p></div></section>

    <section><div className="mb-4 flex items-end justify-between"><div><p className="text-[9px] font-black uppercase tracking-widest text-slate-500">Catálogo</p><h3 className="mt-1 text-lg font-bold text-white">Cursos disponibles próximamente</h3></div><span className="rounded-full border border-amber-400/20 bg-amber-400/10 px-3 py-1 text-[9px] font-black uppercase tracking-wider text-amber-300">Acceso temporalmente bloqueado</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{courses.map(({ title,description,modules,Icon,accent }) => <article key={title} className="relative overflow-hidden rounded-2xl border border-white/[0.07] bg-[#0b1017]/90 p-5"><div className={`absolute inset-0 bg-gradient-to-br ${accent} opacity-70`}/><div className="relative"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl border border-white/10 bg-black/25"><Icon className="h-5 w-5 text-white"/></div><div className="flex h-8 w-8 items-center justify-center rounded-lg border border-amber-400/20 bg-amber-400/10"><Lock className="h-3.5 w-3.5 text-amber-300"/></div></div><h4 className="mt-6 text-base font-black text-white">{title}</h4><p className="mt-2 min-h-10 text-[10px] leading-4 text-slate-400">{description}</p><div className="mt-5 flex items-center justify-between border-t border-white/5 pt-4"><span className="flex items-center gap-1.5 text-[9px] text-slate-500"><PlayCircle className="h-3.5 w-3.5"/>{modules} módulos</span><span className="flex items-center gap-1.5 text-[9px] font-bold text-amber-300"><Clock3 className="h-3.5 w-3.5"/>Próximamente</span></div><button disabled className="mt-4 flex w-full cursor-not-allowed items-center justify-center gap-2 rounded-xl border border-white/5 bg-white/[0.035] py-2.5 text-[10px] font-bold text-slate-600"><Lock className="h-3.5 w-3.5"/>Curso bloqueado</button></div></article>)}</div></section>

    <section className="rounded-3xl border border-violet-400/15 bg-gradient-to-r from-violet-500/10 via-cyan-500/5 to-transparent p-5 sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border border-violet-400/20 bg-violet-400/10"><BookOpen className="h-5 w-5 text-violet-300"/></div><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-violet-300">Documentación</p><h3 className="mt-1 text-lg font-black text-white">Dossier de onboarding Althera</h3><p className="mt-1 text-[10px] text-slate-400">Consulta los procesos, pautas y documentación oficial del equipo comercial.</p></div></div><button onClick={onOpenDocumentation} className="flex shrink-0 items-center justify-center gap-2 rounded-xl bg-violet-500 px-5 py-3 text-xs font-black text-white shadow-lg shadow-violet-500/15 transition hover:bg-violet-400"><FileText className="h-4 w-4"/>Abrir dossier y PDF</button></div></section>
  </div>;
}
