import assert from 'node:assert/strict';
import { buildCommercialCashout, isCommercialCashout } from '../src/utils/commercialCashout';
const account = {id:'com_test',name:'Comercial de prueba',email:'test@example.com'};
const payout = {id:'pay_test',comercialId:account.id,amount:124.99008264462812,date:'2026-09-07T16:45:50.266Z',status:'completed' as const,bankAccount:'Efectivo',paymentMethod:'cash' as const};
const cash = buildCommercialCashout(account,payout)!;
assert.equal(cash.amount,124.99);
assert.equal(cash.paymentMethod,'cash');
assert.equal(cash.paymentAccount,undefined);
assert.equal(cash.description,'Cashout comercial · Comercial de prueba');
assert.equal(cash.status,'paid');
assert.equal(buildCommercialCashout(account,payout)!.id,cash.id);
assert.ok(isCommercialCashout(cash));
assert.equal(buildCommercialCashout(account,{...payout,paymentMethod:'transfer'})!.paymentAccount,'revolut_pro');
assert.equal(buildCommercialCashout(account,{...payout,paymentMethod:'stripe'}),null);
assert.equal(buildCommercialCashout(account,{...payout,stripeTransferId:'tr_test'}),null);
assert.equal(buildCommercialCashout(account,{...payout,status:'failed'}),null);
assert.equal(buildCommercialCashout(account,{...payout,paymentMethod:undefined}),null);
assert.throws(()=>buildCommercialCashout(account,{...payout,amount:NaN}));
assert.throws(()=>buildCommercialCashout(account,{...payout,date:'invalid'}));
console.log('Cashout: métodos, redondeo, identidad estable y exclusión de Stripe/fallidos verificados.');
