import assert from 'node:assert/strict';
import type { FinanceTransaction, Invoice } from '../src/types';
import { attachChargeToInvoice, acknowledgeHistoricalPayment } from '../src/utils/invoiceAttachment';
import { matchesExportSource, exportTotals } from '../src/utils/financeExport';
import { isAutomaticCommissionEligible } from '../src/utils/commission';

const invoice: Invoice = { id: 'AL-test', clientId: 'client', clientName: 'Cliente', clientEmail: '', date: '2026-09-01', dueDate: '2026-09-01', status: 'paid', items: [], subtotal: 100, taxPercentage: 21, taxAmount: 21, total: 121 };
const charge: FinanceTransaction = { id: 'charge', clientId: 'client', type: 'income', category: 'Ventas', status: 'paid', amount: 60.5, date: '2026-09-30', description: 'Servicio', paymentMethod: 'stripe', isInitialSale: true };
const linked = attachChargeToInvoice(invoice, charge);
assert.equal(linked.total, 181.5);
assert.equal(linked.subtotal, 150);
assert.equal(linked.taxAmount, 31.5);
assert.equal(linked.status, 'paid');
assert.equal(linked.items[0].pendingTxId, charge.id);
assert.deepEqual(attachChargeToInvoice(linked, charge), linked);
assert.equal(attachChargeToInvoice(invoice, { ...charge, status: 'pending' }).status, 'sent');
assert.equal(attachChargeToInvoice({ ...invoice, status: 'sent' }, charge).status, 'sent');
assert.throws(() => attachChargeToInvoice(invoice, { ...charge, invoiceId: 'other' }));
assert.throws(() => attachChargeToInvoice(invoice, { ...charge, clientId: 'other' }));
const acknowledged = acknowledgeHistoricalPayment({ ...charge, status: 'pending', description: 'Cuota 3 (Pendiente)' });
assert.equal(acknowledged.status, 'paid');
assert.equal(acknowledged.description, 'Cuota 3');
assert.equal(acknowledged.id, charge.id);
assert.equal(acknowledged.date, charge.date);
assert.equal(acknowledged.amount, charge.amount);
assert.equal(matchesExportSource(acknowledged, 'all'), false);
assert.equal(exportTotals([acknowledged]).income, 0);
assert.equal(isAutomaticCommissionEligible(acknowledged), false);
console.log('Invoice attachment: totals, retry deduplication, client boundaries and historical payment exclusions passed.');

// Legacy invoice lines can retain pending flags after their receipt was paid.
const { reconcileInvoicePayments } = await import('../src/utils/invoiceAttachment');
const installmentInvoice: Invoice = { ...invoice, total: 960, items: [1,2,3].map(n => ({id:`line${n}`, pendingTxId:`quota${n}`, description:'Web', quantity:1, unitPrice:320/1.21, total:320/1.21, grossAmount:320, isPending:n>1})) };
const receipts = [1,2,3].map(n => ({...charge, id:`quota${n}`, amount:320, invoiceId:invoice.id, excludedFromLedger:n===3}));
const repaired = reconcileInvoicePayments(installmentInvoice, receipts);
assert.equal(repaired.status, 'paid');
assert.deepEqual(repaired.items.map(item => item.isPending), [false,false,false]);
assert.equal(repaired.total,960);
assert.equal(receipts[2].excludedFromLedger,true);
assert.equal(reconcileInvoicePayments(repaired, receipts.map(tx => tx.id==='quota2' ? {...tx,status:'pending' as const}:tx)).items[1].isPending,true);
assert.equal(reconcileInvoicePayments(repaired, receipts.map(tx => tx.id==='quota2' ? {...tx,status:'pending' as const}:tx)).status,'sent');
assert.equal(reconcileInvoicePayments(installmentInvoice, []),installmentInvoice);
const legacy = {...installmentInvoice,items:installmentInvoice.items.map(item => ({...item,pendingTxId:undefined}))};
assert.equal(reconcileInvoicePayments(legacy,receipts).items.some(item=>item.isPending),false);
assert.equal(reconcileInvoicePayments(legacy,receipts.slice(0,1)).items[1].isPending,true);
console.log('Invoice payment reconciliation: all paid receipts, partial payment, legacy links and ledger exclusion passed.');
