import assert from 'node:assert/strict';
import type {FinanceTransaction} from '../src/types';
import {getAutomaticCommissionableNetVolume} from '../src/utils/commission';
const base:FinanceTransaction={id:'first',type:'income',category:'Ventas',amount:825,date:'2026-09-08',status:'pending',isInitialSale:true,comercialId:'commercial'};
const history:FinanceTransaction[]=[{...base,id:'previous-1',amount:756.19,status:'paid'},{...base,id:'previous-2',amount:756.19,status:'paid'}];
const transactions=[...history,base,{...base,id:'second',date:'2026-10-08'}];
const paidOut=getAutomaticCommissionableNetVolume(history)*0.1;
const calculate=(items:FinanceTransaction[])=>({ready:Math.round(Math.max(0,getAutomaticCommissionableNetVolume(items.filter(t=>t.status==='paid'))*0.1-paidOut)*100)/100,pending:Math.round(getAutomaticCommissionableNetVolume(items.filter(t=>t.status==='pending'))*0.1*100)/100});
assert.deepEqual(calculate(transactions),{ready:0,pending:136.36});
const collected=transactions.map(t=>t.id==='first'?{...t,status:'paid' as const}:t);
assert.deepEqual(calculate(collected),{ready:68.18,pending:68.18});
assert.deepEqual(calculate(collected.map(t=>t.id==='first'?{...t,status:'pending' as const}:t)),{ready:0,pending:136.36});
console.log('Cuotas: cobro parcial libera 68,18 €, mantiene 68,18 € pendientes y respeta liquidaciones anteriores.');
