import assert from 'node:assert/strict';
import type { FinanceTransaction, Invoice } from '../src/types';
import { attachChargeToInvoice, acknowledgeHistoricalPayment } from '../src/utils/invoiceAttachment';
import { matchesExportSource, exportTotals } from '../src/utils/financeExport';
import { isAutomaticCommissionEligible } from '../src/utils/commission';

const invoice: Invoice = { id: 'AL-test', clientId: 'client', clientName: 'Cliente', clientEmail: '', date: '2026-09-01', dueDate: '2026-09-01', status: 'paid', items: [], subtotal: 100, taxPercentage: 21, taxAmount: 21, total: 121 };
const charge: FinanceTransaction = { id: 'charge', clientId: 'client', type: 'income', category: 'Ventas', status: 'paid', amount: 60.5, date: '2026-09-30', description: 'Servicio', paymentMethod: 'stripe', isInitialSale: true };
const linked = attachChargeToInvoice(invoice, charge);
assert.equal(linked.total, 181.5);
assert.equal(linked.subtotal, 150);
assert.equal(linked.taxAmount, 31.5);
assert.equal(linked.status, 'paid');
assert.equal(linked.items[0].pendingTxId, charge.id);
assert.deepEqual(attachChargeToInvoice(linked, charge), linked);
assert.equal(attachChargeToInvoice(invoice, { ...charge, status: 'pending' }).status, 'sent');
assert.equal(attachChargeToInvoice({ ...invoice, status: 'sent' }, charge).status, 'sent');
assert.throws(() => attachChargeToInvoice(invoice, { ...charge, invoiceId: 'other' }));
assert.throws(() => attachChargeToInvoice(invoice, { ...charge, clientId: 'other' }));
const acknowledged = acknowledgeHistoricalPayment({ ...charge, status: 'pending', description: 'Cuota 3 (Pendiente)' });
assert.equal(acknowledged.status, 'paid');
assert.equal(acknowledged.description, 'Cuota 3');
assert.equal(acknowledged.id, charge.id);
assert.equal(acknowledged.date, charge.date);
assert.equal(acknowledged.amount, charge.amount);
assert.equal(matchesExportSource(acknowledged, 'all'), false);
assert.equal(exportTotals([acknowledged]).income, 0);
assert.equal(isAutomaticCommissionEligible(acknowledged), false);
console.log('Invoice attachment: totals, retry deduplication, client boundaries and historical payment exclusions passed.');
